### ISSUE TITLE
App gets removed from app folder and placed in the global grid when it's added to favorites

### ISSUE THREAD

**Issue by Wolpertinger** [stuarthayhurst/alphabetical-grid-extension#47]
**Describe the issue**
I have enabled the setting to _show favorites on the app grid_. When I add an app from an app folder to favorites it's getting removed from that folder and placed in the global app grid. Trying to drag it back into the folder does not work.

**Expected behavior**
The app should remain in the app folder.

This happens on Fedora 35 with Gnome 41.1.

**Comment by stuarthayhurst** [comment]
Thanks for the report, I'll see what I can do.

**Comment by stuarthayhurst** [comment]
Looking at the code, there are several issues that would need fixing, and it's kind of out of scope of the project. I've removed support for showing favourites in the app grid, as [this](https://extensions.gnome.org/extension/4485/favourites-in-appgrid/) extension does exactly what this extension would do for it, but better.
I've tested their extension with mine, and it works fine, and the issue you discovered is fixed in that extension, but not released yet.

Thanks!
