### ISSUE TITLE
[Feature request] Add an option for a separate first page that doesn't get sorted

### ISSUE THREAD

**Issue by mihalycsaba** [stuarthayhurst/alphabetical-grid-extension#91]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Maybe an option to select apps for the first page and those will stay on the first page and don't get sorted, like pinning. Maybe a simpler solution to just exclude apps from the sorting that are on the first page .

**Can you work on it?**
I can't.

**Additional context**
I just like to keep a few often used apps on the first page, but it would be nice if the others would be somehow organized.

**Comment by mihalycsaba** [comment]
It would be enough if it leaves out the items already on the first page. It should be the default, so it won't mess up existing  arrangements.

**Comment by stuarthayhurst** [comment]
Hm, I'm not sure I agree with making it default, as I'm pretty sure I'd start getting bug reports with people complaining the extension doesn't work because their apps aren't being sorted, because they didn't realise they need to turn a setting off.

It also seems a little counter-intuitive to have an extension to sort applications not sort them all by default. I'd rather the extension does exactly what it says it will be default, and have an additional setting to configure the behaviour, like the existing settings for folder position and whether their contents are ordered.

Either way, I'll implement the feature soonish (probably within a week or two) when I get some time, and we can decide on a default after that if you're not convinced :)

**Comment by stuarthayhurst** [comment]
That approach didn't work, maybe a list of exemptions would be easier, by just moving them to the start and preserving order or something, but the user interface won't be as simple for that

**Comment by stuarthayhurst** [comment]
I'm pretty short on time and as far as I can tell, however this is implemented, it's going to need a considerable rewrite of the extension. This isn't so bad, but it will require the extension to be much more invasive in its monkey patching of the shell, needing a lot more maintenance in the future as well.

Closing as won't fix, but I'm more than happy to review / accept pull requests to implement this if anyone else wants to spend the time on it :)

**Comment by mihalycsaba** [comment]
> I'm pretty short on time and as far as I can tell, however this is implemented, it's going to need a considerable rewrite of the extension. This isn't so bad, but it will require the extension to be much more invasive in its monkey patching of the shell, needing a lot more maintenance in the future as well.
> 
> Closing as won't fix, but I'm more than happy to review / accept pull requests to implement this if anyone else wants to spend the time on it :)

Maybe modify only the sorting, so it will put some apps in the beginning of the list? Without messing much with the shell itself. Also make the sorting manual so it won't reorganize the pages after they were manually modified. It would help tremendously, instead of making it manually.
